### PR TITLE
Add option for setting sleep_between_fetches and cleaned up return codes for failed apply / delete

### PR DESCRIPTION
**Pull request by markus7811**
We are using stack_master a in our ci environment. This pull request would fix 2 of our major problems with stack_master.

1. stack_master makes a lot of api requests. If you are running a lot of stack_updates you can reach the api limit for the cloudformation api really easy. So i made it possible to set the `sleep_between_fetches` interval vial the stack_master.yml file (and changed the default value to 30 seconds - i think this would be really enough, as cloudformation takes some time to create resources and within pipelines you don't care for about 30 extra seconds for finishing the pipeline). This would lower the api calls by factor 30 and has even the ability to change this value.

2. I changed the exit codes for apply and delete operations, that fail. At the moment stack_master mostly exits with an exit code of 0 (everything ok). So our pipeline is allways green, even if the operations (apply, delete, ...) fail. Now, the success state of the commands is evaluated and stack_master exits with 1, if the success state is not true. 
Solves: https://github.com/envato/stack_master/issues/235

It would be nice, if you would accept these Request. Please tell me, what you want to be changed.
(and excuse my bad ruby and chaos commits - it's my first time working with github and ruby)

### CODE REVIEW

**Comment by markus7811** [comment]
I was able to fix the rspec for apply, but have no idea at the moment how to fix the delete spec

**Comment by markus7811** [comment]
ok, the tests that are now failing have nothing to do with my changes in my opinion :-)

**Comment by markus7811** [comment]
ok, it was my mistake

**Comment by markus7811** [comment]
So because now validating a broken template fails with 1 i think the cucumber test breaks - but i have no idea how to fix this behaviour

**Comment by patrobinson** [comment]
Hey @markus7811 thanks for the PR!

Firstly these two problems (exit codes and api rate limiting) are seperate concerns and as such I'd like to see seperate PRs for them. This enables us to have a discussion about each one individually and not let any concerns about one feature prevent the other feature from being merged. I'm very happy to see the exit code be more descriptive and would be happy to help with failing tests to get that over the line.

Secondly, I don't think the approach of letting the user determine how long we sleep for is the best user experience. Instead I imagine solving this problem by catching rate limiting errors from the API and exponentially backing off and retrying, as [described in the AWS documentation](https://docs.aws.amazon.com/general/latest/gr/api-retries.html). This would allow us to deal with this without forcing the user to think about or tune a sleep interval.

**Pull request closed without merging**
