### PR TITLE
add print command to show compiled template

### PR DESCRIPTION
**Pull request by rbayerl**
Fixes https://github.com/envato/stack_master/issues/140

### CODE REVIEW

**Comment by rbayerl** [comment]
`sfn print` deals with compile time parameters by prompting the user. `stack_master` has parameter files to avoid this behavior so I've opted to pull in compile time parameters from the parameter file.

`stack_master print` will work without any parameter file as long as there are no compile time parameters. If there are compile time parameters in the template that do not have default values then those values will need to be populated in the parameter file for the stack.

**Comment by rbayerl** [comment]
@patrobinson anything else needed here?

**Comment by patrobinson** [comment]
@viraptor this implements the same functionality you were working on. Can we use this PR instead?

**Comment by viraptor** [comment]
I don't mind either version.
One difference I spotted is that this one always outputs json, but my version does {json,rb} -> json and yaml -> yaml.

**Comment by patrobinson** [comment]
Oh right we already merged that

@rbayerl sorry this was super-seeded by #245 which I'll release a new version for shortly.

**Comment by rbayerl** [comment]
:+1: works for me

**Pull request closed without merging**
