### PR TITLE
adjust the Prompter to use #gets instead of #getch, so we can pipe the 'yes' command to stack_master and run autonomously

### PR DESCRIPTION
**Pull request by redterror**
Also slightly expand the acceptable affirmative answers to include "yes" and ignore case.

### CODE REVIEW

**Comment by stevehodgkiss** [comment]
Would a new command line option `-y` (like `apt-get`) make more sense for this scenario?

**Comment by redterror** [comment]
I considered that, but this was almost zero work and did the job.

**Comment by lethalpaga** [comment]
Funnily enough I was just working on the same issue. My solution is still a WIP and I don't know when I'll have time to work on it.
FYI https://github.com/envato/stack_master/compare/master...lethalpaga:fix/interactive
Feel free to vampirise it if you want.

**Comment by stevehodgkiss** [comment]
Closing in favour of https://github.com/envato/stack_master/pull/71

Thanks!

**Pull request closed without merging**
