### PR TITLE
Cloudformation service role support

### PR DESCRIPTION
**Pull request by oliver-schoenherr**
Initial support of Cloudformation Service Roles: 

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html

### CODE REVIEW

**Comment by berniedurfee-ge** [comment]
Definitely would love to see this get merged in. Anything else need to be done?

**Comment by patrobinson** [comment]
I'll merge this now and create a new release later today.

**Comment by berniedurfee-ge** [comment]
Awesome, thanks!!

**Comment by patrobinson** [comment]
v0.13.0 has been released

**Pull request merged**
