### PR TITLE
Add latest AMI by tags resolver

### PR DESCRIPTION
**Pull request by stevehodgkiss**
Automatically resolver the latest (by creation date) AMI ID that matches a given set of tags.

The value is expected to look like:

```YAML
web_ami:
  latest_ami_by_tags: role=myapp-web,more-tags=more-values
```

cc @simpsora @gstamp @andrewjhumphrey

### CODE REVIEW

**Comment by gstamp** [comment]
Docs?

**Comment by stevehodgkiss** [comment]
@gstamp updated.

**Comment by gstamp** [comment]
:+1:

**Comment by simpsora** [comment]
:+1:

**Comment by tguo** [comment]
:+1:

**Pull request merged**
